//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string IdTercero { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string Zona { get; set; }
        public string Ruta { get; set; }
        public string Telefonos { get; set; }
        public string Condiciones { get; set; }
        public Nullable<double> SaldoDeudor { get; set; }
        public string CedulaRif { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public string TipoPrecio { get; set; }
        public Nullable<bool> Nuevo { get; set; }
    }
}
