//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentosProductos = new HashSet<DocumentosProducto>();
        }
    
        public string IdDocumento { get; set; }
        public string IdTercero { get; set; }
        public string IdVendedor { get; set; }
        public string TipoCuenta { get; set; }
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> TasaIVA { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Status { get; set; }
        public string IdSesion { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public Nullable<bool> Seleccion { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public string Control { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBs { get; set; }
        public Nullable<double> Fletes { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> TarjetaDebito { get; set; }
        public Nullable<double> TarjetaCredito { get; set; }
        public Nullable<double> Deposito { get; set; }
        public Nullable<double> Transferencias { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> DeudaAnterior { get; set; }
        public string Condiciones { get; set; }
        public Nullable<double> PesoFactura { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public string CedulaRif { get; set; }
        public string Razonsocial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosProducto> DocumentosProductos { get; set; }
    }
}
