//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosProducto
    {
        public string IdDetalleDocumento { get; set; }
        public string IdDocumento { get; set; }
        public string IdProducto { get; set; }
        public string IdServidor { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Comentarios { get; set; }
        public Nullable<double> ExistenciaAnterior { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> CostoIva { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioIva { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<bool> BloqueoPrecio { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> Precio3 { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBs { get; set; }
        public Nullable<double> MontoNeto { get; set; }
        public string RealizadoPor { get; set; }
        public Nullable<bool> SolicitaServidor { get; set; }
        public Nullable<double> PesoUnitario { get; set; }
        public Nullable<double> PesoTotal { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Pvs { get; set; }
        public Nullable<double> Precio4 { get; set; }
        public Nullable<double> Utilidad { get; set; }
        public Nullable<double> Utilidad2 { get; set; }
        public Nullable<double> Utilidad3 { get; set; }
        public Nullable<double> Utilidad4 { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Documento Documento { get; set; }
    }
}
