//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosDetalle
    {
        public string IdPagoDetalle { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<double> Monto { get; set; }
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public string IdRegistroPago { get; set; }
    
        public virtual RegistroPago RegistroPago { get; set; }
    }
}
