//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public string Id { get; set; }
        public string Empresa { get; set; }
        public string EmpresaDireccion { get; set; }
        public string Equipo { get; set; }
        public string Servidor { get; set; }
        public string BaseDeDatos { get; set; }
    }
}
