//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosDetalle
    {
        public string IdPedido { get; set; }
        public string IdProducto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBolivares { get; set; }
        public Nullable<double> PrecioNeto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> ExistenciaPrevia { get; set; }
        public string IdDetalle { get; set; }
        public Nullable<double> PesoUnitario { get; set; }
        public Nullable<double> PesoTotal { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Pvs { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
