//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidosDetalles = new List<PedidosDetalle>();
        }
    
        public string IdPedido { get; set; }
        public string IdCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Numero { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> TarjetaDebito { get; set; }
        public Nullable<double> TarjetaCredito { get; set; }
        public Nullable<double> Transferencias { get; set; }
        public Nullable<double> Saldo { get; set; }
        public Nullable<double> Deposito { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> Peso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosDetalle> PedidosDetalles { get; set; }
    }
}
