//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public string IdProducto { get; set; }
        public string Descripcion { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> Precio3 { get; set; }
        public Nullable<double> Precio4 { get; set; }
        public Nullable<double> Pvs { get; set; }
        public Nullable<double> Existencia { get; set; }
        public Nullable<double> Iva { get; set; }
        public string Grupo { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> PrecioIVA { get; set; }
        public Nullable<double> PrecioIVA2 { get; set; }
        public Nullable<double> PrecioIVA3 { get; set; }
        public Nullable<double> PrecioIVA4 { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> Maximo { get; set; }
        public Nullable<double> Minimo { get; set; }
        public string IdProveedor { get; set; }
        public Nullable<double> Precio5 { get; set; }
        public Nullable<double> PrecioIVA5 { get; set; }
    }
}
