//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistroPago()
        {
            this.PagosDetalles = new HashSet<PagosDetalle>();
        }
    
        public string IdRegistroPago { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public string Modulo { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public Nullable<double> MontoPagar { get; set; }
        public Nullable<double> SaldoPendiente { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> Deposito { get; set; }
        public string BancoCheque { get; set; }
        public string NumeroCheque { get; set; }
        public string NumeroDeposito { get; set; }
        public string BancoDeposito { get; set; }
        public string Transferencia { get; set; }
        public string RazonSocial { get; set; }
        public string IdTecero { get; set; }
        public Nullable<double> MontoPagado { get; set; }
        public Nullable<double> Cheque2 { get; set; }
        public string NumeroCheque2 { get; set; }
        public string BancoCheque2 { get; set; }
        public Nullable<double> Deposito2 { get; set; }
        public string BancoDeposito2 { get; set; }
        public string NumeroDeposito2 { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Detalles { get; set; }
        public Nullable<bool> Enviado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagosDetalle> PagosDetalles { get; set; }
    }
}
