//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bancos()
        {
            this.BancosMovimientos = new HashSet<BancosMovimientos>();
        }
    
        public string IdBanco { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<double> SaldoInicial { get; set; }
        public Nullable<double> SaldoActual { get; set; }
        public string TipoCuenta { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BancosMovimientos> BancosMovimientos { get; set; }
    }
}
