//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class BancosMovimientos
    {
        public string IdMovimiento { get; set; }
        public string IdBanco { get; set; }
        public string IdSesion { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Numero { get; set; }
        public string Detalles { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> Debe { get; set; }
        public Nullable<double> Haber { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string IdBeneficiario { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<bool> Conciliado { get; set; }
    
        public virtual Bancos Bancos { get; set; }
    }
}
