//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public string IdGrupo { get; set; }
        public string Codigo { get; set; }
        public string Grupo { get; set; }
        public Nullable<double> Utilidad1 { get; set; }
        public Nullable<double> Utilidad2 { get; set; }
        public Nullable<double> Utilidad3 { get; set; }
        public Nullable<double> TasaIVA { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
