//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroVentas
    {
        public string IdLibroVentas { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public string Factura { get; set; }
        public string Control { get; set; }
        public string NotaCredito { get; set; }
        public string NotaDebito { get; set; }
        public string TipoTransaccion { get; set; }
        public string Comprobante { get; set; }
        public string FacturaAfectada { get; set; }
        public Nullable<double> MontoIncluyentoIva { get; set; }
        public Nullable<double> VentasNoGravadas { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> ImpuestoIva { get; set; }
        public Nullable<double> IvaRetenido { get; set; }
        public string NroRegistroMaquinaFiscal { get; set; }
        public string ReporteZ { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoExentoNoContribuyentes { get; set; }
        public Nullable<double> BaseImponibleNoContribuyentes { get; set; }
        public Nullable<double> ImpuestoIvaNoContribuyentes { get; set; }
    }
}
