//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public string IdParametros { get; set; }
        public string Empresa { get; set; }
        public string EmpresaDireccion { get; set; }
        public string EmpresaCiudad { get; set; }
        public string EmpresaRif { get; set; }
        public string EmpresaTelefonos { get; set; }
        public Nullable<double> TasaIVA { get; set; }
        public string TipoImpresora { get; set; }
        public string TipoImpresion { get; set; }
        public string PuertoImpresora { get; set; }
        public Nullable<double> Utilidad1 { get; set; }
        public Nullable<double> Utilidad2 { get; set; }
        public Nullable<double> Utilidad3 { get; set; }
        public Nullable<double> RetencionISLR { get; set; }
        public Nullable<double> RetencionIVA { get; set; }
        public Nullable<double> CostoDolar { get; set; }
        public string RegistroMaquinaFiscal { get; set; }
        public Nullable<int> UltimoReporteZ { get; set; }
        public Nullable<int> Correlativofactura { get; set; }
        public Nullable<int> CorrelativoDevolucion { get; set; }
        public string CalculoPrecios { get; set; }
        public string TipoIva { get; set; }
        public string Vendedor { get; set; }
        public Nullable<double> Utilidad4 { get; set; }
        public string NotaPieDeFactura { get; set; }
        public Nullable<int> TopeItemsFactura { get; set; }
        public Nullable<bool> FacturarSinExistencia { get; set; }
        public Nullable<double> TasaIvaB { get; set; }
        public Nullable<double> TasaIvaC { get; set; }
    }
}
