//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecibosDetalles
    {
        public int IdReciboDetalles { get; set; }
        public string IdRecibo { get; set; }
        public string IdDocumento { get; set; }
        public string IdCuenta { get; set; }
        public Nullable<double> MontoAbono { get; set; }
        public string Tipo { get; set; }
    
        public virtual Recibos Recibos { get; set; }
    }
}
