//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibos()
        {
            this.RecibosDetalles = new HashSet<RecibosDetalles>();
            this.RecibosPagos = new HashSet<RecibosPagos>();
        }
    
        public string IdRecibo { get; set; }
        public string IdSesion { get; set; }
        public string IdTercero { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public string NumeroRecibo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public string TipoRecibo { get; set; }
        public bool Activo { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheques { get; set; }
        public Nullable<double> Tarjetas { get; set; }
        public Nullable<double> Depositos { get; set; }
        public Nullable<double> Transferencias { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> RetencionISLR { get; set; }
        public Nullable<double> RetencionIVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosDetalles> RecibosDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosPagos> RecibosPagos { get; set; }
    }
}
