//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPagos
    {
        public string IdRegistroPago { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public string Modulo { get; set; }
        public string Tipo { get; set; }
        public string Documento { get; set; }
        public Nullable<double> MontoPagar { get; set; }
        public Nullable<double> MontoPagado { get; set; }
        public Nullable<double> SaldoPendiente { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> TDebito { get; set; }
        public Nullable<double> TCredito { get; set; }
        public Nullable<double> Deposito { get; set; }
        public string BancoCheque { get; set; }
        public string NumeroCheque { get; set; }
        public string PuntoDebito { get; set; }
        public string PuntoCredito { get; set; }
        public string NumeroDeposito { get; set; }
        public string BancoDeposito { get; set; }
        public string Transferencia { get; set; }
        public Nullable<double> RetencionISLR { get; set; }
        public Nullable<double> RetencionIVA { get; set; }
        public string RazonSocial { get; set; }
        public string IdTercero { get; set; }
        public string Detalles { get; set; }
        public Nullable<double> NotaCredito { get; set; }
        public Nullable<double> Cheque2 { get; set; }
        public Nullable<double> Deposito2 { get; set; }
        public string NumeroCheque2 { get; set; }
        public string BancoCheque2 { get; set; }
        public string NumeroDeposito2 { get; set; }
        public string BancoDeposito2 { get; set; }
        public string NumeroRetencion { get; set; }
        public Nullable<System.DateTime> FechaRetencion { get; set; }
    }
}
