//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPagosExternosDetalles
    {
        public string IdRegistroPagoExternoDetalle { get; set; }
        public string IdRegistroPagosExterno { get; set; }
        public string IDDocumento { get; set; }
        public string Numero { get; set; }
        public Nullable<double> Monto { get; set; }
    
        public virtual RegistroPagosExternos RegistroPagosExternos { get; set; }
    }
}
