//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoroEntities : DbContext
    {
        public SoroEntities()
            : base("name=SoroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuxiliarBancos> AuxiliarBancos { get; set; }
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<BancosMovimientos> BancosMovimientos { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Contadores> Contadores { get; set; }
        public virtual DbSet<Cuentas> Cuentas { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<DocumentosProductos> DocumentosProductos { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<LibroCompras> LibroCompras { get; set; }
        public virtual DbSet<LibroInventarios> LibroInventarios { get; set; }
        public virtual DbSet<LibroVentas> LibroVentas { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Recibos> Recibos { get; set; }
        public virtual DbSet<RecibosDetalles> RecibosDetalles { get; set; }
        public virtual DbSet<RecibosPagos> RecibosPagos { get; set; }
        public virtual DbSet<RegistroPagoProveedor> RegistroPagoProveedor { get; set; }
        public virtual DbSet<RegistroPagoProveedorDetalles> RegistroPagoProveedorDetalles { get; set; }
        public virtual DbSet<RegistroPagos> RegistroPagos { get; set; }
        public virtual DbSet<RegistroPagosDetalles> RegistroPagosDetalles { get; set; }
        public virtual DbSet<RegistroPagosExternos> RegistroPagosExternos { get; set; }
        public virtual DbSet<RegistroPagosExternosDetalles> RegistroPagosExternosDetalles { get; set; }
        public virtual DbSet<Retenciones> Retenciones { get; set; }
        public virtual DbSet<RetencionesDetalles> RetencionesDetalles { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Temporal> Temporal { get; set; }
        public virtual DbSet<Terceros> Terceros { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosDerechos> UsuariosDerechos { get; set; }
        public virtual DbSet<CuentasPendientes> CuentasPendientes { get; set; }
        public virtual DbSet<TercerosConSaldos> TercerosConSaldos { get; set; }
        public virtual DbSet<VistaCompras> VistaCompras { get; set; }
        public virtual DbSet<VistaDocumento> VistaDocumento { get; set; }
        public virtual DbSet<VistaFactura> VistaFactura { get; set; }
        public virtual DbSet<VistaProductos> VistaProductos { get; set; }
        public virtual DbSet<VistaRecibo> VistaRecibo { get; set; }
        public virtual DbSet<VistaCuentas> VistaCuentas { get; set; }
    }
}
