//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TercerosConSaldos
    {
        public string IdTercero { get; set; }
        public string RazonSocial { get; set; }
        public string CedulaRif { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public string Email { get; set; }
        public Nullable<double> DiasCredito { get; set; }
        public Nullable<double> LimiteCredito { get; set; }
        public string Tipo { get; set; }
        public string TipoContribuyente { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public string Ciudad { get; set; }
        public string Zona { get; set; }
        public string Estado { get; set; }
        public string TipoPrecio { get; set; }
        public string Condiciones { get; set; }
        public string TipoCuenta { get; set; }
        public Nullable<double> MontoPendiente { get; set; }
    }
}
