//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaFactura
    {
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string Comentarios { get; set; }
        public string RazonSocial { get; set; }
        public string CedulaRif { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public Nullable<double> DiasCredito { get; set; }
        public string Status { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string ComentariosProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> CostoIva { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioIva { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public string IdDocumento { get; set; }
        public string Vendedor { get; set; }
        public string IdVendedor { get; set; }
        public Nullable<int> Año { get; set; }
        public string Control { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBs { get; set; }
        public Nullable<double> DescuentoPorcentajeItem { get; set; }
        public Nullable<double> DescuentoBsItem { get; set; }
        public Nullable<double> MontoNeto { get; set; }
        public string RealizadoPor { get; set; }
        public Nullable<bool> SolicitaServidor { get; set; }
        public Nullable<double> ExistenciaAnterior { get; set; }
        public Nullable<double> Fletes { get; set; }
        public Nullable<double> PesoTotal { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> TarjetaDebito { get; set; }
        public Nullable<double> TarjetaCredito { get; set; }
        public Nullable<double> Deposito { get; set; }
        public Nullable<double> DeudaAnterior { get; set; }
        public Nullable<double> Cambio { get; set; }
        public Nullable<double> Pvs { get; set; }
        public string Condiciones { get; set; }
        public string Ciudad { get; set; }
        public string Zona { get; set; }
        public string Estado { get; set; }
        public string IdTercero { get; set; }
        public string IdProducto { get; set; }
        public string Concepto { get; set; }
    }
}
