//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaProductos
    {
        public string IdProducto { get; set; }
        public string IdGrupo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Referencia { get; set; }
        public Nullable<double> Existencia { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioIVA { get; set; }
        public Nullable<double> Precio2 { get; set; }
        public Nullable<double> Precio3 { get; set; }
        public Nullable<bool> BloqueoPrecio { get; set; }
        public Nullable<bool> LlevaInventario { get; set; }
        public Nullable<bool> SolicitaServidor { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Tipo { get; set; }
        public Nullable<double> CostoActual { get; set; }
        public Nullable<double> CostoDolares { get; set; }
        public Nullable<double> Minimo { get; set; }
        public Nullable<double> Maximo { get; set; }
        public string Grupo { get; set; }
        public Nullable<double> CantidadVentaPorDefecto { get; set; }
        public string CodigoBarras { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> DescuentoMaximo { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<double> Precio4 { get; set; }
        public Nullable<double> PrecioIva2 { get; set; }
        public Nullable<double> PrecioIva3 { get; set; }
        public Nullable<double> PrecioIva4 { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<double> PVP { get; set; }
        public string IdProveedor { get; set; }
        public Nullable<double> PrecioIva5 { get; set; }
    }
}
