//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCompras
    {
        public string CedulaRif { get; set; }
        public string RazonSocial { get; set; }
        public string Telefonos { get; set; }
        public string Direccion { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> ExistenciaAnterior { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> CostoIva { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioIva { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Total { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<double> TasaIva { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBs { get; set; }
        public Nullable<double> MontoNeto { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public Nullable<double> Expr2 { get; set; }
        public Nullable<double> Fletes { get; set; }
        public string Comentarios { get; set; }
    }
}
