//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaRecibo
    {
        public string IdSesion { get; set; }
        public string IdRecibo { get; set; }
        public string IdTercero { get; set; }
        public Nullable<System.DateTime> Momento { get; set; }
        public string NumeroRecibo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public string TipoRecibo { get; set; }
        public bool Activo { get; set; }
        public Nullable<double> Monto { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheques { get; set; }
        public Nullable<double> Tarjetas { get; set; }
        public Nullable<double> Depositos { get; set; }
        public Nullable<double> Transferencias { get; set; }
        public Nullable<double> Cambio { get; set; }
        public string FormaPago { get; set; }
        public Nullable<double> MontoPago { get; set; }
        public string Detalles { get; set; }
        public string Numero { get; set; }
        public string Banco { get; set; }
        public string IdDocumento { get; set; }
        public Nullable<double> MontoAbono { get; set; }
        public string Tipo { get; set; }
        public string NumeroDocumento { get; set; }
        public string TipoDocumento { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string RazonSocial { get; set; }
        public string CedulaRif { get; set; }
    }
}
