//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaDocumento
    {
        public string Numero { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<double> BaseImponible { get; set; }
        public Nullable<double> MontoExento { get; set; }
        public Nullable<double> MontoIva { get; set; }
        public Nullable<double> TasaIVA { get; set; }
        public Nullable<double> MontoTotal { get; set; }
        public Nullable<double> Saldo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string RazonSocial { get; set; }
        public string CedulaRif { get; set; }
        public string Direccion { get; set; }
        public string Telefonos { get; set; }
        public Nullable<double> DiasCredito { get; set; }
        public string IdDocumento { get; set; }
        public string IdTercero { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Seleccion { get; set; }
        public string Vendedor { get; set; }
        public string IdVendedor { get; set; }
        public Nullable<int> Año { get; set; }
        public string Control { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> DescuentoPorcentaje { get; set; }
        public Nullable<double> DescuentoBs { get; set; }
        public Nullable<double> Fletes { get; set; }
        public Nullable<double> Efectivo { get; set; }
        public Nullable<double> Cheque { get; set; }
        public Nullable<double> TarjetaDebito { get; set; }
        public Nullable<double> TarjetaCredito { get; set; }
        public Nullable<double> Deposito { get; set; }
        public Nullable<double> DeudaAnterior { get; set; }
        public Nullable<double> Cambio { get; set; }
        public string Condiciones { get; set; }
        public string Ciudad { get; set; }
        public string Zona { get; set; }
        public string Estado { get; set; }
        public Nullable<double> PesoFactura { get; set; }
        public Nullable<bool> Enviado { get; set; }
        public string Concepto { get; set; }
    }
}
