//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace HK
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Data : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Data object using the connection string found in the 'Data' section of the application configuration file.
        /// </summary>
        public Data() : base("name=Data", "Data")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Data object.
        /// </summary>
        public Data(string connectionString) : base(connectionString, "Data")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Data object.
        /// </summary>
        public Data(EntityConnection connection) : base(connection, "Data")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contadore> Contadores
        {
            get
            {
                if ((_Contadores == null))
                {
                    _Contadores = base.CreateObjectSet<Contadore>("Contadores");
                }
                return _Contadores;
            }
        }
        private ObjectSet<Contadore> _Contadores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Parametros> Parametros
        {
            get
            {
                if ((_Parametros == null))
                {
                    _Parametros = base.CreateObjectSet<Parametros>("Parametros");
                }
                return _Parametros;
            }
        }
        private ObjectSet<Parametros> _Parametros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Proveedore> Proveedores
        {
            get
            {
                if ((_Proveedores == null))
                {
                    _Proveedores = base.CreateObjectSet<Proveedore>("Proveedores");
                }
                return _Proveedores;
            }
        }
        private ObjectSet<Proveedore> _Proveedores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Retenciones> Retenciones
        {
            get
            {
                if ((_Retenciones == null))
                {
                    _Retenciones = base.CreateObjectSet<Retenciones>("Retenciones");
                }
                return _Retenciones;
            }
        }
        private ObjectSet<Retenciones> _Retenciones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RetencionesISLR> RetencionesISLR
        {
            get
            {
                if ((_RetencionesISLR == null))
                {
                    _RetencionesISLR = base.CreateObjectSet<RetencionesISLR>("RetencionesISLR");
                }
                return _RetencionesISLR;
            }
        }
        private ObjectSet<RetencionesISLR> _RetencionesISLR;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contadores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContadores(Contadore contadore)
        {
            base.AddObject("Contadores", contadore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Parametros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParametros(Parametros parametros)
        {
            base.AddObject("Parametros", parametros);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Proveedores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProveedores(Proveedore proveedore)
        {
            base.AddObject("Proveedores", proveedore);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Retenciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRetenciones(Retenciones retenciones)
        {
            base.AddObject("Retenciones", retenciones);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RetencionesISLR EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRetencionesISLR(RetencionesISLR retencionesISLR)
        {
            base.AddObject("RetencionesISLR", retencionesISLR);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Datos", Name="Contadore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contadore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contadore object.
        /// </summary>
        /// <param name="variable">Initial value of the Variable property.</param>
        public static Contadore CreateContadore(global::System.String variable)
        {
            Contadore contadore = new Contadore();
            contadore.Variable = variable;
            return contadore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Variable
        {
            get
            {
                return _Variable;
            }
            set
            {
                if (_Variable != value)
                {
                    OnVariableChanging(value);
                    ReportPropertyChanging("Variable");
                    _Variable = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Variable");
                    OnVariableChanged();
                }
            }
        }
        private global::System.String _Variable;
        partial void OnVariableChanging(global::System.String value);
        partial void OnVariableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private Nullable<global::System.Double> _Valor;
        partial void OnValorChanging(Nullable<global::System.Double> value);
        partial void OnValorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Datos", Name="Parametros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Parametros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Parametros object.
        /// </summary>
        /// <param name="idParametros">Initial value of the IdParametros property.</param>
        public static Parametros CreateParametros(global::System.String idParametros)
        {
            Parametros parametros = new Parametros();
            parametros.IdParametros = idParametros;
            return parametros;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdParametros
        {
            get
            {
                return _IdParametros;
            }
            set
            {
                if (_IdParametros != value)
                {
                    OnIdParametrosChanging(value);
                    ReportPropertyChanging("IdParametros");
                    _IdParametros = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdParametros");
                    OnIdParametrosChanged();
                }
            }
        }
        private global::System.String _IdParametros;
        partial void OnIdParametrosChanging(global::System.String value);
        partial void OnIdParametrosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CedulaRif
        {
            get
            {
                return _CedulaRif;
            }
            set
            {
                OnCedulaRifChanging(value);
                ReportPropertyChanging("CedulaRif");
                _CedulaRif = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CedulaRif");
                OnCedulaRifChanged();
            }
        }
        private global::System.String _CedulaRif;
        partial void OnCedulaRifChanging(global::System.String value);
        partial void OnCedulaRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TasaIva
        {
            get
            {
                return _TasaIva;
            }
            set
            {
                OnTasaIvaChanging(value);
                ReportPropertyChanging("TasaIva");
                _TasaIva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TasaIva");
                OnTasaIvaChanged();
            }
        }
        private Nullable<global::System.Double> _TasaIva;
        partial void OnTasaIvaChanging(Nullable<global::System.Double> value);
        partial void OnTasaIvaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PorcentajeRetencion
        {
            get
            {
                return _PorcentajeRetencion;
            }
            set
            {
                OnPorcentajeRetencionChanging(value);
                ReportPropertyChanging("PorcentajeRetencion");
                _PorcentajeRetencion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PorcentajeRetencion");
                OnPorcentajeRetencionChanged();
            }
        }
        private Nullable<global::System.Double> _PorcentajeRetencion;
        partial void OnPorcentajeRetencionChanging(Nullable<global::System.Double> value);
        partial void OnPorcentajeRetencionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefonos
        {
            get
            {
                return _Telefonos;
            }
            set
            {
                OnTelefonosChanging(value);
                ReportPropertyChanging("Telefonos");
                _Telefonos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefonos");
                OnTelefonosChanged();
            }
        }
        private global::System.String _Telefonos;
        partial void OnTelefonosChanging(global::System.String value);
        partial void OnTelefonosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PeriodoFiscal
        {
            get
            {
                return _PeriodoFiscal;
            }
            set
            {
                OnPeriodoFiscalChanging(value);
                ReportPropertyChanging("PeriodoFiscal");
                _PeriodoFiscal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PeriodoFiscal");
                OnPeriodoFiscalChanged();
            }
        }
        private global::System.String _PeriodoFiscal;
        partial void OnPeriodoFiscalChanging(global::System.String value);
        partial void OnPeriodoFiscalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Datos", Name="Proveedore")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proveedore : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Proveedore object.
        /// </summary>
        /// <param name="idProveedor">Initial value of the IdProveedor property.</param>
        public static Proveedore CreateProveedore(global::System.String idProveedor)
        {
            Proveedore proveedore = new Proveedore();
            proveedore.IdProveedor = idProveedor;
            return proveedore;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdProveedor
        {
            get
            {
                return _IdProveedor;
            }
            set
            {
                if (_IdProveedor != value)
                {
                    OnIdProveedorChanging(value);
                    ReportPropertyChanging("IdProveedor");
                    _IdProveedor = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdProveedor");
                    OnIdProveedorChanged();
                }
            }
        }
        private global::System.String _IdProveedor;
        partial void OnIdProveedorChanging(global::System.String value);
        partial void OnIdProveedorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CedulaRif
        {
            get
            {
                return _CedulaRif;
            }
            set
            {
                OnCedulaRifChanging(value);
                ReportPropertyChanging("CedulaRif");
                _CedulaRif = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CedulaRif");
                OnCedulaRifChanged();
            }
        }
        private global::System.String _CedulaRif;
        partial void OnCedulaRifChanging(global::System.String value);
        partial void OnCedulaRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefonos
        {
            get
            {
                return _Telefonos;
            }
            set
            {
                OnTelefonosChanging(value);
                ReportPropertyChanging("Telefonos");
                _Telefonos = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefonos");
                OnTelefonosChanged();
            }
        }
        private global::System.String _Telefonos;
        partial void OnTelefonosChanging(global::System.String value);
        partial void OnTelefonosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LimiteCredito
        {
            get
            {
                return _LimiteCredito;
            }
            set
            {
                OnLimiteCreditoChanging(value);
                ReportPropertyChanging("LimiteCredito");
                _LimiteCredito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimiteCredito");
                OnLimiteCreditoChanged();
            }
        }
        private Nullable<global::System.Double> _LimiteCredito;
        partial void OnLimiteCreditoChanging(Nullable<global::System.Double> value);
        partial void OnLimiteCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DiasCredito
        {
            get
            {
                return _DiasCredito;
            }
            set
            {
                OnDiasCreditoChanging(value);
                ReportPropertyChanging("DiasCredito");
                _DiasCredito = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiasCredito");
                OnDiasCreditoChanged();
            }
        }
        private Nullable<global::System.Int32> _DiasCredito;
        partial void OnDiasCreditoChanging(Nullable<global::System.Int32> value);
        partial void OnDiasCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contacto
        {
            get
            {
                return _Contacto;
            }
            set
            {
                OnContactoChanging(value);
                ReportPropertyChanging("Contacto");
                _Contacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contacto");
                OnContactoChanged();
            }
        }
        private global::System.String _Contacto;
        partial void OnContactoChanging(global::System.String value);
        partial void OnContactoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Activo;
        partial void OnActivoChanging(Nullable<global::System.Boolean> value);
        partial void OnActivoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Datos", Name="Retenciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Retenciones : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Retenciones object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Retenciones CreateRetenciones(global::System.String id)
        {
            Retenciones retenciones = new Retenciones();
            retenciones.Id = id;
            return retenciones;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumeroDeOperacion
        {
            get
            {
                return _NumeroDeOperacion;
            }
            set
            {
                OnNumeroDeOperacionChanging(value);
                ReportPropertyChanging("NumeroDeOperacion");
                _NumeroDeOperacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumeroDeOperacion");
                OnNumeroDeOperacionChanged();
            }
        }
        private Nullable<global::System.Int32> _NumeroDeOperacion;
        partial void OnNumeroDeOperacionChanging(Nullable<global::System.Int32> value);
        partial void OnNumeroDeOperacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CedulaRif
        {
            get
            {
                return _CedulaRif;
            }
            set
            {
                OnCedulaRifChanging(value);
                ReportPropertyChanging("CedulaRif");
                _CedulaRif = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CedulaRif");
                OnCedulaRifChanged();
            }
        }
        private global::System.String _CedulaRif;
        partial void OnCedulaRifChanging(global::System.String value);
        partial void OnCedulaRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreRazonSocial
        {
            get
            {
                return _NombreRazonSocial;
            }
            set
            {
                OnNombreRazonSocialChanging(value);
                ReportPropertyChanging("NombreRazonSocial");
                _NombreRazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreRazonSocial");
                OnNombreRazonSocialChanged();
            }
        }
        private global::System.String _NombreRazonSocial;
        partial void OnNombreRazonSocialChanging(global::System.String value);
        partial void OnNombreRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PeriodoImpositivo
        {
            get
            {
                return _PeriodoImpositivo;
            }
            set
            {
                OnPeriodoImpositivoChanging(value);
                ReportPropertyChanging("PeriodoImpositivo");
                _PeriodoImpositivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PeriodoImpositivo");
                OnPeriodoImpositivoChanged();
            }
        }
        private global::System.String _PeriodoImpositivo;
        partial void OnPeriodoImpositivoChanging(global::System.String value);
        partial void OnPeriodoImpositivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaDocumento
        {
            get
            {
                return _FechaDocumento;
            }
            set
            {
                OnFechaDocumentoChanging(value);
                ReportPropertyChanging("FechaDocumento");
                _FechaDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaDocumento");
                OnFechaDocumentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaDocumento;
        partial void OnFechaDocumentoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoOperacion
        {
            get
            {
                return _TipoOperacion;
            }
            set
            {
                OnTipoOperacionChanging(value);
                ReportPropertyChanging("TipoOperacion");
                _TipoOperacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoOperacion");
                OnTipoOperacionChanged();
            }
        }
        private global::System.String _TipoOperacion;
        partial void OnTipoOperacionChanging(global::System.String value);
        partial void OnTipoOperacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoDocumento
        {
            get
            {
                return _TipoDocumento;
            }
            set
            {
                OnTipoDocumentoChanging(value);
                ReportPropertyChanging("TipoDocumento");
                _TipoDocumento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoDocumento");
                OnTipoDocumentoChanged();
            }
        }
        private global::System.String _TipoDocumento;
        partial void OnTipoDocumentoChanging(global::System.String value);
        partial void OnTipoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RifAgenteRetencion
        {
            get
            {
                return _RifAgenteRetencion;
            }
            set
            {
                OnRifAgenteRetencionChanging(value);
                ReportPropertyChanging("RifAgenteRetencion");
                _RifAgenteRetencion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RifAgenteRetencion");
                OnRifAgenteRetencionChanged();
            }
        }
        private global::System.String _RifAgenteRetencion;
        partial void OnRifAgenteRetencionChanging(global::System.String value);
        partial void OnRifAgenteRetencionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroDocumento
        {
            get
            {
                return _NumeroDocumento;
            }
            set
            {
                OnNumeroDocumentoChanging(value);
                ReportPropertyChanging("NumeroDocumento");
                _NumeroDocumento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroDocumento");
                OnNumeroDocumentoChanged();
            }
        }
        private global::System.String _NumeroDocumento;
        partial void OnNumeroDocumentoChanging(global::System.String value);
        partial void OnNumeroDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroControlDocumento
        {
            get
            {
                return _NumeroControlDocumento;
            }
            set
            {
                OnNumeroControlDocumentoChanging(value);
                ReportPropertyChanging("NumeroControlDocumento");
                _NumeroControlDocumento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroControlDocumento");
                OnNumeroControlDocumentoChanged();
            }
        }
        private global::System.String _NumeroControlDocumento;
        partial void OnNumeroControlDocumentoChanging(global::System.String value);
        partial void OnNumeroControlDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoDocumento
        {
            get
            {
                return _MontoDocumento;
            }
            set
            {
                OnMontoDocumentoChanging(value);
                ReportPropertyChanging("MontoDocumento");
                _MontoDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoDocumento");
                OnMontoDocumentoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoDocumento;
        partial void OnMontoDocumentoChanging(Nullable<global::System.Double> value);
        partial void OnMontoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BaseImponible
        {
            get
            {
                return _BaseImponible;
            }
            set
            {
                OnBaseImponibleChanging(value);
                ReportPropertyChanging("BaseImponible");
                _BaseImponible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseImponible");
                OnBaseImponibleChanged();
            }
        }
        private Nullable<global::System.Double> _BaseImponible;
        partial void OnBaseImponibleChanging(Nullable<global::System.Double> value);
        partial void OnBaseImponibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoIvaRetenido
        {
            get
            {
                return _MontoIvaRetenido;
            }
            set
            {
                OnMontoIvaRetenidoChanging(value);
                ReportPropertyChanging("MontoIvaRetenido");
                _MontoIvaRetenido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoIvaRetenido");
                OnMontoIvaRetenidoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoIvaRetenido;
        partial void OnMontoIvaRetenidoChanging(Nullable<global::System.Double> value);
        partial void OnMontoIvaRetenidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroDocumentoAfectado
        {
            get
            {
                return _NumeroDocumentoAfectado;
            }
            set
            {
                OnNumeroDocumentoAfectadoChanging(value);
                ReportPropertyChanging("NumeroDocumentoAfectado");
                _NumeroDocumentoAfectado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroDocumentoAfectado");
                OnNumeroDocumentoAfectadoChanged();
            }
        }
        private global::System.String _NumeroDocumentoAfectado;
        partial void OnNumeroDocumentoAfectadoChanging(global::System.String value);
        partial void OnNumeroDocumentoAfectadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroComprobante
        {
            get
            {
                return _NumeroComprobante;
            }
            set
            {
                OnNumeroComprobanteChanging(value);
                ReportPropertyChanging("NumeroComprobante");
                _NumeroComprobante = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroComprobante");
                OnNumeroComprobanteChanged();
            }
        }
        private global::System.String _NumeroComprobante;
        partial void OnNumeroComprobanteChanging(global::System.String value);
        partial void OnNumeroComprobanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoExentoIva
        {
            get
            {
                return _MontoExentoIva;
            }
            set
            {
                OnMontoExentoIvaChanging(value);
                ReportPropertyChanging("MontoExentoIva");
                _MontoExentoIva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoExentoIva");
                OnMontoExentoIvaChanged();
            }
        }
        private Nullable<global::System.Double> _MontoExentoIva;
        partial void OnMontoExentoIvaChanging(Nullable<global::System.Double> value);
        partial void OnMontoExentoIvaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Alicuota
        {
            get
            {
                return _Alicuota;
            }
            set
            {
                OnAlicuotaChanging(value);
                ReportPropertyChanging("Alicuota");
                _Alicuota = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Alicuota");
                OnAlicuotaChanged();
            }
        }
        private Nullable<global::System.Double> _Alicuota;
        partial void OnAlicuotaChanging(Nullable<global::System.Double> value);
        partial void OnAlicuotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroExpediente
        {
            get
            {
                return _NumeroExpediente;
            }
            set
            {
                OnNumeroExpedienteChanging(value);
                ReportPropertyChanging("NumeroExpediente");
                _NumeroExpediente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroExpediente");
                OnNumeroExpedienteChanged();
            }
        }
        private global::System.String _NumeroExpediente;
        partial void OnNumeroExpedienteChanging(global::System.String value);
        partial void OnNumeroExpedienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoIva
        {
            get
            {
                return _MontoIva;
            }
            set
            {
                OnMontoIvaChanging(value);
                ReportPropertyChanging("MontoIva");
                _MontoIva = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoIva");
                OnMontoIvaChanged();
            }
        }
        private Nullable<global::System.Double> _MontoIva;
        partial void OnMontoIvaChanging(Nullable<global::System.Double> value);
        partial void OnMontoIvaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaComprobante
        {
            get
            {
                return _FechaComprobante;
            }
            set
            {
                OnFechaComprobanteChanging(value);
                ReportPropertyChanging("FechaComprobante");
                _FechaComprobante = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaComprobante");
                OnFechaComprobanteChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaComprobante;
        partial void OnFechaComprobanteChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaComprobanteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Periodo
        {
            get
            {
                return _Periodo;
            }
            set
            {
                OnPeriodoChanging(value);
                ReportPropertyChanging("Periodo");
                _Periodo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Periodo");
                OnPeriodoChanged();
            }
        }
        private global::System.String _Periodo;
        partial void OnPeriodoChanging(global::System.String value);
        partial void OnPeriodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PorcentajeRetencion
        {
            get
            {
                return _PorcentajeRetencion;
            }
            set
            {
                OnPorcentajeRetencionChanging(value);
                ReportPropertyChanging("PorcentajeRetencion");
                _PorcentajeRetencion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PorcentajeRetencion");
                OnPorcentajeRetencionChanged();
            }
        }
        private Nullable<global::System.Double> _PorcentajeRetencion;
        partial void OnPorcentajeRetencionChanging(Nullable<global::System.Double> value);
        partial void OnPorcentajeRetencionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotaCredito
        {
            get
            {
                return _NotaCredito;
            }
            set
            {
                OnNotaCreditoChanging(value);
                ReportPropertyChanging("NotaCredito");
                _NotaCredito = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotaCredito");
                OnNotaCreditoChanged();
            }
        }
        private global::System.String _NotaCredito;
        partial void OnNotaCreditoChanging(global::System.String value);
        partial void OnNotaCreditoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NotaDebito
        {
            get
            {
                return _NotaDebito;
            }
            set
            {
                OnNotaDebitoChanging(value);
                ReportPropertyChanging("NotaDebito");
                _NotaDebito = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NotaDebito");
                OnNotaDebitoChanged();
            }
        }
        private global::System.String _NotaDebito;
        partial void OnNotaDebitoChanging(global::System.String value);
        partial void OnNotaDebitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Sustraendo
        {
            get
            {
                return _Sustraendo;
            }
            set
            {
                OnSustraendoChanging(value);
                ReportPropertyChanging("Sustraendo");
                _Sustraendo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sustraendo");
                OnSustraendoChanged();
            }
        }
        private Nullable<global::System.Double> _Sustraendo;
        partial void OnSustraendoChanging(Nullable<global::System.Double> value);
        partial void OnSustraendoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Datos", Name="RetencionesISLR")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RetencionesISLR : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RetencionesISLR object.
        /// </summary>
        /// <param name="idRetencionISLR">Initial value of the IdRetencionISLR property.</param>
        public static RetencionesISLR CreateRetencionesISLR(global::System.String idRetencionISLR)
        {
            RetencionesISLR retencionesISLR = new RetencionesISLR();
            retencionesISLR.IdRetencionISLR = idRetencionISLR;
            return retencionesISLR;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdRetencionISLR
        {
            get
            {
                return _IdRetencionISLR;
            }
            set
            {
                if (_IdRetencionISLR != value)
                {
                    OnIdRetencionISLRChanging(value);
                    ReportPropertyChanging("IdRetencionISLR");
                    _IdRetencionISLR = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdRetencionISLR");
                    OnIdRetencionISLRChanged();
                }
            }
        }
        private global::System.String _IdRetencionISLR;
        partial void OnIdRetencionISLRChanging(global::System.String value);
        partial void OnIdRetencionISLRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Numero
        {
            get
            {
                return _Numero;
            }
            set
            {
                OnNumeroChanging(value);
                ReportPropertyChanging("Numero");
                _Numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Numero");
                OnNumeroChanged();
            }
        }
        private global::System.String _Numero;
        partial void OnNumeroChanging(global::System.String value);
        partial void OnNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CedulaRif
        {
            get
            {
                return _CedulaRif;
            }
            set
            {
                OnCedulaRifChanging(value);
                ReportPropertyChanging("CedulaRif");
                _CedulaRif = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CedulaRif");
                OnCedulaRifChanged();
            }
        }
        private global::System.String _CedulaRif;
        partial void OnCedulaRifChanging(global::System.String value);
        partial void OnCedulaRifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreRazonSocial
        {
            get
            {
                return _NombreRazonSocial;
            }
            set
            {
                OnNombreRazonSocialChanging(value);
                ReportPropertyChanging("NombreRazonSocial");
                _NombreRazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreRazonSocial");
                OnNombreRazonSocialChanged();
            }
        }
        private global::System.String _NombreRazonSocial;
        partial void OnNombreRazonSocialChanging(global::System.String value);
        partial void OnNombreRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Periodo
        {
            get
            {
                return _Periodo;
            }
            set
            {
                OnPeriodoChanging(value);
                ReportPropertyChanging("Periodo");
                _Periodo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Periodo");
                OnPeriodoChanged();
            }
        }
        private global::System.String _Periodo;
        partial void OnPeriodoChanging(global::System.String value);
        partial void OnPeriodoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> MontoDocumento
        {
            get
            {
                return _MontoDocumento;
            }
            set
            {
                OnMontoDocumentoChanging(value);
                ReportPropertyChanging("MontoDocumento");
                _MontoDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoDocumento");
                OnMontoDocumentoChanged();
            }
        }
        private Nullable<global::System.Double> _MontoDocumento;
        partial void OnMontoDocumentoChanging(Nullable<global::System.Double> value);
        partial void OnMontoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BaseImponible
        {
            get
            {
                return _BaseImponible;
            }
            set
            {
                OnBaseImponibleChanging(value);
                ReportPropertyChanging("BaseImponible");
                _BaseImponible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BaseImponible");
                OnBaseImponibleChanged();
            }
        }
        private Nullable<global::System.Double> _BaseImponible;
        partial void OnBaseImponibleChanging(Nullable<global::System.Double> value);
        partial void OnBaseImponibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PorcentajeRetencion
        {
            get
            {
                return _PorcentajeRetencion;
            }
            set
            {
                OnPorcentajeRetencionChanging(value);
                ReportPropertyChanging("PorcentajeRetencion");
                _PorcentajeRetencion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PorcentajeRetencion");
                OnPorcentajeRetencionChanged();
            }
        }
        private Nullable<global::System.Double> _PorcentajeRetencion;
        partial void OnPorcentajeRetencionChanging(Nullable<global::System.Double> value);
        partial void OnPorcentajeRetencionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ImpuestoRetenido
        {
            get
            {
                return _ImpuestoRetenido;
            }
            set
            {
                OnImpuestoRetenidoChanging(value);
                ReportPropertyChanging("ImpuestoRetenido");
                _ImpuestoRetenido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImpuestoRetenido");
                OnImpuestoRetenidoChanged();
            }
        }
        private Nullable<global::System.Double> _ImpuestoRetenido;
        partial void OnImpuestoRetenidoChanging(Nullable<global::System.Double> value);
        partial void OnImpuestoRetenidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumeroFactura
        {
            get
            {
                return _NumeroFactura;
            }
            set
            {
                OnNumeroFacturaChanging(value);
                ReportPropertyChanging("NumeroFactura");
                _NumeroFactura = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumeroFactura");
                OnNumeroFacturaChanged();
            }
        }
        private global::System.String _NumeroFactura;
        partial void OnNumeroFacturaChanging(global::System.String value);
        partial void OnNumeroFacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaFactura
        {
            get
            {
                return _FechaFactura;
            }
            set
            {
                OnFechaFacturaChanging(value);
                ReportPropertyChanging("FechaFactura");
                _FechaFactura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaFactura");
                OnFechaFacturaChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaFactura;
        partial void OnFechaFacturaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaFacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Sustraendo
        {
            get
            {
                return _Sustraendo;
            }
            set
            {
                OnSustraendoChanging(value);
                ReportPropertyChanging("Sustraendo");
                _Sustraendo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sustraendo");
                OnSustraendoChanged();
            }
        }
        private Nullable<global::System.Double> _Sustraendo;
        partial void OnSustraendoChanging(Nullable<global::System.Double> value);
        partial void OnSustraendoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Control
        {
            get
            {
                return _Control;
            }
            set
            {
                OnControlChanging(value);
                ReportPropertyChanging("Control");
                _Control = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Control");
                OnControlChanged();
            }
        }
        private global::System.String _Control;
        partial void OnControlChanging(global::System.String value);
        partial void OnControlChanged();

        #endregion

    
    }

    #endregion

    
}
